// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test1', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 880 })
    await driver.findElement(By.css(".bg-purple-600")).click()
    await driver.findElement(By.css(".nav__header__list__element:nth-child(2) > li")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.css(".MuiMenuItem-root")).click()
  })
})
